"""create fisac tables

Revision ID: 0001_init
Revises: 
Create Date: 2026-08-17 21:41:41.042216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_init'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Bootstraps the schema itself so a fresh database needs no manual setup
    # before this migration runs - the connecting role just needs CREATE
    # privilege on the database (true by default for a database's own owner,
    # e.g. a managed Postgres provider's auto-created user).
    op.execute('CREATE SCHEMA IF NOT EXISTS fisac')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('is_company', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('vat_applicable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('visa_payment_day', sa.SmallInteger(), nullable=True),
    sa.Column('sort_key', sa.String(collation='C'), nullable=False),
    sa.CheckConstraint('visa_payment_day IS NULL OR (visa_payment_day >= 1 AND visa_payment_day <= 31)', name='ck_accounts_visa_payment_day_range'),
    sa.PrimaryKeyConstraint('id'),
    schema='fisac'
    )
    op.create_index('ix_accounts_sort_key', 'accounts', ['sort_key'], unique=False, schema='fisac')
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tax_deduction_rate', sa.Numeric(precision=5, scale=2), server_default='100', nullable=False),
    sa.Column('vat_deduction_rate', sa.Numeric(precision=5, scale=2), server_default='100', nullable=False),
    sa.Column('sort_key', sa.String(collation='C'), nullable=False),
    sa.CheckConstraint('tax_deduction_rate >= 0 AND tax_deduction_rate <= 100', name='ck_categories_tax_deduction_rate_range'),
    sa.CheckConstraint('vat_deduction_rate >= 0 AND vat_deduction_rate <= 100', name='ck_categories_vat_deduction_rate_range'),
    sa.ForeignKeyConstraint(['account_id'], ['fisac.accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_categories_account_name'),
    schema='fisac'
    )
    op.create_index('ix_categories_account_sort_key', 'categories', ['account_id', 'sort_key'], unique=False, schema='fisac')
    op.create_index(op.f('ix_fisac_categories_account_id'), 'categories', ['account_id'], unique=False, schema='fisac')
    op.create_table('flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('REVENUE', 'EXPENSE', name='flow_kind'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.Enum('DIRECT_DEBIT', 'BANK_TRANSFER', 'VISA', name='payment_method'), nullable=True),
    sa.Column('paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('reverse_charge', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_key', sa.String(collation='C'), nullable=False),
    sa.CheckConstraint('payment_method IS NOT NULL OR payment_date IS NULL', name='ck_flows_no_method_no_payment_date'),
    sa.ForeignKeyConstraint(['account_id'], ['fisac.accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['fisac.categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='fisac'
    )
    op.create_index(op.f('ix_fisac_flows_account_id'), 'flows', ['account_id'], unique=False, schema='fisac')
    op.create_index(op.f('ix_fisac_flows_batch_id'), 'flows', ['batch_id'], unique=False, schema='fisac')
    op.create_index(op.f('ix_fisac_flows_category_id'), 'flows', ['category_id'], unique=False, schema='fisac')
    op.create_index(op.f('ix_fisac_flows_invoice_date'), 'flows', ['invoice_date'], unique=False, schema='fisac')
    op.create_index(op.f('ix_fisac_flows_kind'), 'flows', ['kind'], unique=False, schema='fisac')
    op.create_index(op.f('ix_fisac_flows_payment_date'), 'flows', ['payment_date'], unique=False, schema='fisac')
    op.create_index('ix_flows_account_payment_date', 'flows', ['account_id', 'payment_date'], unique=False, schema='fisac')
    op.create_index('ix_flows_account_sort_key', 'flows', ['account_id', 'sort_key'], unique=False, schema='fisac')
    op.create_table('flow_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('amount_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('sort_key', sa.String(collation='C'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['fisac.flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fisac'
    )
    op.create_index(op.f('ix_fisac_flow_lines_flow_id'), 'flow_lines', ['flow_id'], unique=False, schema='fisac')
    op.create_index('ix_flow_lines_flow_sort_key', 'flow_lines', ['flow_id', 'sort_key'], unique=False, schema='fisac')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flow_lines_flow_sort_key', table_name='flow_lines', schema='fisac')
    op.drop_index(op.f('ix_fisac_flow_lines_flow_id'), table_name='flow_lines', schema='fisac')
    op.drop_table('flow_lines', schema='fisac')
    op.drop_index('ix_flows_account_sort_key', table_name='flows', schema='fisac')
    op.drop_index('ix_flows_account_payment_date', table_name='flows', schema='fisac')
    op.drop_index(op.f('ix_fisac_flows_payment_date'), table_name='flows', schema='fisac')
    op.drop_index(op.f('ix_fisac_flows_kind'), table_name='flows', schema='fisac')
    op.drop_index(op.f('ix_fisac_flows_invoice_date'), table_name='flows', schema='fisac')
    op.drop_index(op.f('ix_fisac_flows_category_id'), table_name='flows', schema='fisac')
    op.drop_index(op.f('ix_fisac_flows_batch_id'), table_name='flows', schema='fisac')
    op.drop_index(op.f('ix_fisac_flows_account_id'), table_name='flows', schema='fisac')
    op.drop_table('flows', schema='fisac')
    op.drop_index(op.f('ix_fisac_categories_account_id'), table_name='categories', schema='fisac')
    op.drop_index('ix_categories_account_sort_key', table_name='categories', schema='fisac')
    op.drop_table('categories', schema='fisac')
    op.drop_index('ix_accounts_sort_key', table_name='accounts', schema='fisac')
    op.drop_table('accounts', schema='fisac')
    # ### end Alembic commands ###
